apiVersion: v1
kind: Service
metadata:
  name: ticket-booking-service
  labels:
    app: ticket-booking-app
spec:
  # Type: Use LoadBalancer to expose the service externally via a public IP
  type: LoadBalancer 
  ports:
    - port: 80
      targetPort: 3000 # The internal container port
      protocol: TCP
      name: http
  selector:
    app: ticket-booking-app # Directs traffic to the running pods
